import ThemeManager from 'react-native-color-theme';

const colors = new ThemeManager({
  whiteTheme: {
    mainColor: 'White',
    statusBarColor: '#fff',
    statusBarStyle: 'dark-content',
    backgroundColor: '#fff',
    textColor: '#000',
    primarySwitchBtnBackground: '#f2f2f2',
    primarySwitchBtnText: '#000',
    secondarySwitchBtnBackground: '#000',
    secondarySwitchBtnText: '#fff',
    simpleBtnBackground: '#fff',
    simpleBtnText: '#000',
    simpleBtnborderColor: '#e6e6e6',
    addLinkTextColor: '#909090',
    primaryGradiantShadow: 'rgba(255,255,255,1)',
    secondaryGradiantShadow: 'rgba(0,0,0,0.0)',
    profileBackgroundColor: '#f2f2f2',
    profilePictureTint: '#ccc',
    textInputBackground: '#f4f4f4',
    textInputBorder: '#e2e2e2',
    addLinksBackgroundColor: '#f9f9f9',
    addLinksBigBtnBackground: '#fff',
    addLinksBigBtnFetured: '#00f',
    addLinksBigBtnTitle: '#000',
    addLinksBigBtnDescription: '#959595',
    tripleBtnBackground: '#f2f2f2',
    tripleBtnTitle: '#000',
    addingLinksTopContainer: '#f2f2f2',
    grayBtn: '#e2e2e2',
    grayBtnText: '#101010',
    addingLinkscsutomizeBtn: '#e2e2e2',
    addingLinkscsutomizeIcon: '#000',
    connectionAddBtnBackground: '#fff',
  },
  blackTheme: {
    mainColor: 'black',
    statusBarColor: '#000',
    statusBarStyle: 'light-content',
    backgroundColor: '#000',
    textColor: '#fff',
    primarySwitchBtnBackground: '#000',
    primarySwitchBtnText: '#fff',
    secondarySwitchBtnBackground: '#f2f2f2',
    secondarySwitchBtnText: '#000',
    simpleBtnborderColor: '#fff',
    addLinkTextColor: '#fff',
    primaryGradiantShadow: 'rgba(0,0,0,1)',
    secondaryGradiantShadow: 'rgba(255,255,255,0)',
    profileBackgroundColor: '#909090',
    profilePictureTint: '#ccc',
    textInputBackground: '#909090',
    textInputBorder: '#ccc',
    addLinksBackgroundColor: '#000',
    addLinksBigBtnBackground: '#303030',
    addLinksBigBtnFetured: '#00ccff',
    addLinksBigBtnTitle: '#fff',
    addLinksBigBtnDescription: '#f2f2f2',
    tripleBtnBackground: '#303030',
    tripleBtnTitle: '#f2f2f2',
    addingLinksTopContainer: '#202020',
    grayBtn: '#303030',
    grayBtnText: '#ccc',
    addingLinkscsutomizeBtn: '#303030',
    addingLinkscsutomizeIcon: '#ccc',
    connectionAddBtnBackground: '#000',
  },
});
export default colors;
